defaults:
  - meta_base

name: anil
n_task: 4
task_update_num: 1

anil_inner_lr: 0.01

# ANIL reqires special gradient updates in backbone
fast_weight: True

# For instantiate API
cls:
  _target_: methods.anil.ANIL
  n_task: ${method.n_task}
  task_update_num: ${method.task_update_num}
  inner_lr: ${method.anil_inner_lr}